housing_listings = [
    {
        "id" : "H1",
        "location": "Boston, USA",
        "safety": "High",
        "housing_type": "Hotel",
        "rental_type": "Private",
        "cost_per_night": 50,
        "amenities": ["Walking", "Eating", "Shopping"],
        "scheduled_dates": ['2025-01-01', '2025-01-02', '2025-01-03'],
        "reviews": ["Great place to stay", "Bad place to stay", "Average place to stay"],
    },
    {
        "id" : "H2",
        "location": "Boston, USA",
        "safety": "Medium",
        "housing_type": "2-bedroom House",
        "rental_type": "Private",
        "cost_per_night": 80,
        "amenities": ["WiFi", "Kitchen", "Balcony"],
        "scheduled_dates": ['2025-02-10', '2025-02-11', '2025-02-12'],
        "reviews": ["Cozy and clean", "Nice host", "Would stay again"],
    },
    {
        "id" : "H3",
        "location": "Boston, USA",
        "safety": "Low",
        "housing_type": "Hostel",
        "rental_type": "Private",
        "cost_per_night": 25,
        "amenities": ["Shared Room", "Breakfast", "Lockers"],
        "scheduled_dates": ['2025-03-15', '2025-03-16', '2025-03-17'],
        "reviews": ["Good for backpackers", "Noisy at night", "Friendly staff"],
    },
    {
        "id" : "H4",
        "location": "Boston, USA",
        "safety": "High",
        "housing_type": "2-bedroom House",
        "rental_type": "Entire",
        "cost_per_night": 150,
        "amenities": ["Pool", "Spa", "Beach Access"],
        "scheduled_dates": ['2025-04-20', '2025-04-21', '2025-04-22'],
        "reviews": ["Luxurious experience", "Great amenities", "Expensive but worth it"],
    },
    {
        "id": "H5",
        "location": "San Francisco, USA",
        "safety": "High",
        "housing_type": "Studio Apartment",
        "rental_type": "Entire",
        "cost_per_night": 200,
        "amenities": ["WiFi", "Kitchen", "Washer", "City View"],
        "scheduled_dates": ['2025-05-10', '2025-05-11', '2025-05-12'],
        "reviews": ["Great location", "Modern and clean", "Bit noisy at night"],
    },
    {
        "id": "H6",
        "location": "Paris, France",
        "safety": "Medium",
        "housing_type": "Hotel",
        "rental_type": "Private",
        "cost_per_night": 120,
        "amenities": ["WiFi", "Breakfast", "Elevator"],
        "scheduled_dates": ['2025-06-01', '2025-06-02', '2025-06-03'],
        "reviews": ["Walkable to sights", "Charming decor", "Small rooms"],
    },
    {
        "id": "H7",
        "location": "Tokyo, Japan",
        "safety": "High",
        "housing_type": "Capsule Hotel",
        "rental_type": "Private",
        "cost_per_night": 60,
        "amenities": ["WiFi", "Shared Bath", "Locker"],
        "scheduled_dates": ['2025-07-14', '2025-07-15', '2025-07-16'],
        "reviews": ["Unique experience", "Very clean", "Compact space"],
    },
    {
        "id": "H8",
        "location": "Reykjavik, Iceland",
        "safety": "High",
        "housing_type": "Cottage",
        "rental_type": "Entire",
        "cost_per_night": 180,
        "amenities": ["Kitchen", "Fireplace", "Parking"],
        "scheduled_dates": ['2025-08-20', '2025-08-21', '2025-08-22'],
        "reviews": ["Cozy and scenic", "Great for Northern Lights", "Quiet area"],
    },
    {
        "id": "H9",
        "location": "Cairo, Egypt",
        "safety": "Medium",
        "housing_type": "Guesthouse",
        "rental_type": "Private",
        "cost_per_night": 40,
        "amenities": ["Air Conditioning", "Breakfast", "Rooftop"],
        "scheduled_dates": ['2025-09-05', '2025-09-06', '2025-09-07'],
        "reviews": ["Friendly host", "Great value", "Basic amenities"],
    },
    {
        "id": "H10",
        "location": "Marrakesh, Morocco",
        "safety": "Medium",
        "housing_type": "Riad",
        "rental_type": "Entire",
        "cost_per_night": 90,
        "amenities": ["Courtyard", "WiFi", "Breakfast"],
        "scheduled_dates": ['2025-10-10', '2025-10-11', '2025-10-12'],
        "reviews": ["Beautiful interiors", "Authentic stay", "Can be hard to find"],
    },
    {
        "id": "H11",
        "location": "Bali, Indonesia",
        "safety": "High",
        "housing_type": "Villa",
        "rental_type": "Entire",
        "cost_per_night": 220,
        "amenities": ["Pool", "Kitchen", "Garden"],
        "scheduled_dates": ['2025-11-01', '2025-11-02', '2025-11-03'],
        "reviews": ["Relaxing retreat", "Great staff", "Private and spacious"],
    },
    {
        "id": "H12",
        "location": "New York, USA",
        "safety": "Low",
        "housing_type": "Hostel",
        "rental_type": "Private",
        "cost_per_night": 35,
        "amenities": ["WiFi", "Shared Kitchen", "Lounge"],
        "scheduled_dates": ['2025-12-15', '2025-12-16', '2025-12-17'],
        "reviews": ["Budget friendly", "Social vibe", "Shared facilities"],
    },
    {
        "id": "H13",
        "location": "Zurich, Switzerland",
        "safety": "High",
        "housing_type": "Hotel",
        "rental_type": "Private",
        "cost_per_night": 250,
        "amenities": ["WiFi", "Gym", "Lake View"],
        "scheduled_dates": ['2026-01-10', '2026-01-11', '2026-01-12'],
        "reviews": ["Spotless rooms", "Great breakfast", "Pricey but worth it"],
    },
    {
        "id": "H14",
        "location": "Mexico City, Mexico",
        "safety": "Medium",
        "housing_type": "2-bedroom House",
        "rental_type": "Entire",
        "cost_per_night": 85,
        "amenities": ["Kitchen", "Washer", "Patio"],
        "scheduled_dates": ['2026-02-20', '2026-02-21', '2026-02-22'],
        "reviews": ["Spacious and central", "Quiet street", "Comfortable beds"],
    },
]

housing_id_dict = {a['id']: a for a in housing_listings}