housing_listings = [
    {
        "id" : 1,
        "location": "Boston, USA",
        "safety": "High",
        "housing_type": "Hotel",
        "rental_type": "Private",
        "cost_per_night": 50,
        "amenities": ["Walking", "Eating", "Shopping"],
        "scheduled_dates": ['2025-01-01', '2025-01-02', '2025-01-03'],
        "reviews": ["Great place to stay", "Bad place to stay", "Average place to stay"],
    },
    {
        "id" : 2,
        "location": "Boston, USA",
        "safety": "Medium",
        "housing_type": "2-bedroom House",
        "rental_type": "Private",
        "cost_per_night": 80,
        "amenities": ["WiFi", "Kitchen", "Balcony"],
        "scheduled_dates": ['2025-02-10', '2025-02-11', '2025-02-12'],
        "reviews": ["Cozy and clean", "Nice host", "Would stay again"],
    },
    {
        "id" : 3,
        "location": "Boston, USA",
        "safety": "Low",
        "housing_type": "Hostel",
        "rental_type": "Private",
        "cost_per_night": 25,
        "amenities": ["Shared Room", "Breakfast", "Lockers"],
        "scheduled_dates": ['2025-03-15', '2025-03-16', '2025-03-17'],
        "reviews": ["Good for backpackers", "Noisy at night", "Friendly staff"],
    },
    {
        "id" : 4,
        "location": "Boston, USA",
        "safety": "High",
        "housing_type": "2-bedroom House",
        "rental_type": "Entire",
        "cost_per_night": 150,
        "amenities": ["Pool", "Spa", "Beach Access"],
        "scheduled_dates": ['2025-04-20', '2025-04-21', '2025-04-22'],
        "reviews": ["Luxurious experience", "Great amenities", "Expensive but worth it"],
    },
]
